name: fritzbox-wlan-password-rotator
services:
  fb-pw-rotator:
    image: phipzzz/fritzbox-wlan-password-rotator:latest
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
      - target: 5000
        published: "5001"
        protocol: tcp
    restart: unless-stopped
    environment:
      - CRONTAB_EXPRESSION=0 3 * * *
      - FB_ADDRESS=192.168.178.1
      - FB_PASSWORD=
      - FB_USER=
      - TZ=Africa/Tunis
      - WEB_PASSWORD=password
      - WLAN_CONFIGURATION=WLANConfiguration3
      - WEB_PAGE_TITLE=WLAN QR-Code
      - WEB_PUBLIC_ENABLED=true
    volumes:
      - type: bind
        source: /DATA/AppData/FritzBox WLAN Password Rotator/app/data
        target: /app/data
    x-casaos:
      ports:
        - container: "5000"
          description:
            en_us: "Web interface for password rotation"
      volumes:
        - container: /app/data
          description:
            en_us: "Data directory for storing temporary files"
x-casaos:
  architectures:
    - "386"
    - amd64
    - arm
    - arm64
    - ppc64le
  main: fb-pw-rotator
  author: yassinyl
  developer: phipzzz
  category: Network
  description:
    en_us: |
      A tool that automatically updates the guest WLAN password of a FRITZ!Box after a defined interval and displays the updated credentials and QR code on a central webpage in your home network.
  icon: https://raw.githubusercontent.com/yassinyl/yl-casa-store/refs/heads/main/Apps/fritzbox-wlan-password-rotator/icon.png
  screenshot_link:
    - https://raw.githubusercontent.com/yassinyl/yl-casa-store/refs/heads/main/Apps/fritzbox-wlan-password-rotator/screenshot-1.png
    - https://raw.githubusercontent.com/yassinyl/yl-casa-store/refs/heads/main/Apps/fritzbox-wlan-password-rotator/screenshot-2.png
  tagline:
    en_us: "Automatically rotate WLAN passwords for FRITZ!Box"
  tips:
    tip_1: "Ensure your FRITZ!Box supports remote password changes."
    tip_2: "Adjust the CRON expression to fit your desired schedule."
  title:
    en_us: FritzBox WLAN Password Rotator
  store_app_id: fritzbox-wlan-password-rotator
  port_map: "5001"
  scheme: http
