name: static-web-server
services:
  static-web-server:
    environment:
      PGID: $PGID
      PUID: $PUID
      TZ: Africa/Tunis
      SERVER_ROOT: /var/public
      SERVER_CONFIG_FILE: /etc/config.toml
    image: joseluisq/static-web-server:2-alpine
    deploy:
      resources:
        reservations:
          memory: 128M
    network_mode: bridge
    ports:
      - target: 80
        published: 80
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/public
        target: /var/public
      - type: bind
        source: /DATA/AppData/$AppID/config.toml
        target: /etc/config.toml
    x-casaos:
      envs:
        - container: SERVER_ROOT
          description:
            en_us: Path to the static files directory.
            fr_fr: Chemin vers le répertoire des fichiers statiques.
        - container: SERVER_CONFIG_FILE
          description:
            en_us: Path to the server configuration file.
            fr_fr: Chemin vers le fichier de configuration du serveur.
        - container: TZ
          description:
            en_us: Timezone for the container.
            fr_fr: Fuseau horaire pour le conteneur.
      ports:
        - container: 80
          description:
            en_us: Web server port.
            fr_fr: Port du serveur Web.
          protocol: tcp
      volumes:
        - container: /var/public
          description:
            en_us: Static files directory.
            fr_fr: Répertoire des fichiers statiques.
        - container: /etc/config.toml
          description:
            en_us: Configuration file for the web server.
            fr_fr: Fichier de configuration pour le serveur Web.
    container_name: static-web-server
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: static-web-server
  developer: joseluisq
  author: joseluisq
  category: Network
  description:
    en_us: |
      A static file web server with custom configurations.
    fr_fr: |
      Un serveur Web de fichiers statiques avec des configurations personnalisées.
  icon: https://cdn.jsdelivr.net/gh/yassinyl/casa7014@refs/heads/main/Apps/static-web-server/icon.png
  tagline:
    en_us: Static Web Server
    fr_fr: Serveur Web Statique
  thumbnail: https://cdn.jsdelivr.net/gh/yassinyl/casa7014@refs/heads/main/Apps/static-web-server/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/yassinyl/casa7014@refs/heads/main/Apps/static-web-server/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/yassinyl/casa7014@refs/heads/main/Apps/static-web-server/screenshot-2.png
  store_app_id: static-web-server
  tips: {}
  title:
    en_us: Static Web Server
  index: /
  port_map: 80
  scheme: http
