name: motioneye-beta
services:
  motioneye:
    image: motioneye-project/motioneye:edge
    deploy:
      resources:
        reservations:
          memory: "64M"
    network_mode: bridge
    ports:
      - "8765:8765"
      - "8081:8081"
    restart: unless-stopped
    environment:
      - TZ=Africa/Tunis
    volumes:
      - /DATA/AppData/motioneye/etc_motioneye:/etc/motioneye
      - /DATA/AppData/motioneye/var_lib_motioneye:/var/lib/motioneye
    container_name: motioneyebeta

x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  author: yassinyl
  category: Utilities
  description:
    en_us: |
      MotionEye is an open-source video surveillance application that manages webcams easily with a graphical interface.
  developer: MotionEye Project
  icon:  https://raw.githubusercontent.com/yassinyl/casa7014/refs/heads/main/Apps/motioneye beta/icon.png
  screenshot_link:
    - https://raw.githubusercontent.com/yassinyl/casa7014/refs/heads/main/Apps/motioneye beta/screenshot-1.png
    - https://raw.githubusercontent.com/yassinyl/casa7014/refs/heads/main/Apps/motioneye beta/screenshot-2.png
    - https://raw.githubusercontent.com/yassinyl/casa7014/refs/heads/main/Apps/motioneye beta/screenshot-3.png
    - https://raw.githubusercontent.com/yassinyl/casa7014/refs/heads/main/Apps/motioneye beta/screenshot-4.png
  thumbnail: https://raw.githubusercontent.com/motioneye-project/motioneye/master/resources/motioneye-logo.png
  main: motioneye-beta
  tagline:
    en_us: "Video surveillance for your cameras"
  title:
    en_us: MotionEye Beta
  scheme: http
  hostname: ""
  port_map: "8765"
  index: "/#!/surveillance"
  tips:
    before_install:
      en_us: |
        MotionEye requires a webcam or IP camera to be connected to function properly. After installation, you can configure and manage your cameras through the web interface at `http://<your_server_ip>:8765`.
